### ISSUE TITLE
Using arrow keys while typing a message causes crash

### ISSUE THREAD

**Issue by ApocalypseCalculator** [BattleMage0231/borz-client#2]
![image](https://user-images.githubusercontent.com/59318806/104849339-23558a00-58b7-11eb-9bf7-42257f839606.png)

After typing a message and hitting enter (not insert) and then pressing an arrow key the client crashes.

**Comment by l2zou** [comment]
Thank you for reporting this bug. It will be fixed in the next commit.

**Comment by l2zou** [comment]
This has been fixed in the latest commit.
